name: CI Check

on: [ push ]

concurrency:
  group: ${{ github.ref }}-check
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Extension SDK
        run: |
          git clone https://github.com/hivemq/hivemq-extension-sdk.git ../hivemq-extension-sdk
          cd ../hivemq-extension-sdk
          git checkout ${GITHUB_REF##*/} || true
          git clone https://github.com/hivemq/hivemq-edge-extension-sdk.git ../hivemq-edge-extension-sdk
          cd ../hivemq-edge-extension-sdk
          git checkout ${GITHUB_REF##*/} || true
          cd ../hivemq-edge
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Check
        run: ./gradlew test :hivemq-edge:forbiddenApis :hivemqEdgeZip
