name: Publish to Docker Hub

on:
  release:
    types: [ published ]

jobs:
  publish:
    environment: mavenCentralPublish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Attach HiveMQ Zip to GitHub Release
        run: ./gradlew :hivemqEdgeZip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/distributions/hivemq-edge-*
          tag: ${{ github.ref }}
          file_glob: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Push To Docker Hub
        run: PUSH_IMAGE=true docker/publish-release.sh
