name: Publish Snapshot to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Extension SDK
        run: |
          git clone https://github.com/hivemq/hivemq-extension-sdk.git ../hivemq-extension-sdk
          cd ../hivemq-extension-sdk
          git checkout ${GITHUB_REF##*/} || true
          git clone https://github.com/hivemq/hivemq-edge-extension-sdk.git ../hivemq-edge-extension-sdk
          cd ../hivemq-edge-extension-sdk
          git checkout ${GITHUB_REF##*/} || true
          cd ../hivemq-edge
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Push Snapshot To Docker Hub
        run: PUSH_IMAGE=true docker/build.sh
